In [45]:
# From https://docs.scipy.org/doc/numpy/user/quickstart.html
import numpy as np

## Learning Numpy

Numpy is a library for Python to deal with homogenous, multi dimensional arrays. 
- These are usually positive integers but not always the case
- Numpy provides the *ndarray* class which is aliased as *array* 
     - Remember this is different than the Python array.array class
     - The Python class only handles 1 dimensional arrays while Numpy is multidimensional
- Dimensions in Numpy are called axes

In [41]:
# Create an array with 1 axis (1 dimensional) with 1-15 (arange is analgous to
# range in Python)
a = np.arange(15)

In [12]:
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [17]:
# Reshape it into a 3x5 array
a = a.reshape(3, 5)

In [18]:
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


### Attributes of arrays

In [23]:
# Number of axes 
a.ndim

2

In [24]:
# Dimensions of the array
a.shape

(3, 5)

In [25]:
# Total number of elements in the array
a.size

15

In [26]:
# The data type of the array. These include standard Python types as well as 
# numpy types
a.dtype

dtype('int32')

In [27]:
# Size in bytes of each element of an array
a.itemsize

4

In [28]:
# The buffer containing the actual elements of the array (usually we'll just 
# use indexes to access the array, including for completeness)
a.data

### Creating Arrays

In [31]:
# Create array from a Python List
a = np.array([2,3,4])

print(a)

[2 3 4]


In [34]:
# Use () to create multidimensional arrays
a = np.array([(1,2,3), (4,5,6)])

print(a)

[[1 2 3]
 [4 5 6]]


In [32]:
# Types will be set automatically
b = np.array([1.4, 2, 3])
b.dtype

dtype('float64')

In [35]:
# Types can also be set explicitly at creation time
b = np.array([ [1,2], [3,4] ], dtype=complex)

print(b)
b.dtype

[[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]]


dtype('complex128')

In [37]:
# Numpy offers methods for creating pre-filled arrays
z = np.zeros( (3,4) )
print(z)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [38]:
o = np.ones( (2,3,4), dtype=np.int16 )
print(o)

[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


In [40]:
# Using np.empty will fill an array with random values
r = np.empty( (2,3) )
print(r)

[[0. 0. 0.]
 [0. 0. 0.]]


### Printing Arrays
How numpy prints multi dimensional arrays:
- The last axis is printed from left to right
- The second to last axis is printed from top to bottom
- The rest are printed top to bottom with each slice separated by an empty line

In [42]:
# One dimensional
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [43]:
# Two dimensional
b = np.arange(12).reshape(4,3)
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [44]:
# Three dimensional
c = np.arange(24).reshape(2,3,4)
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


### Matrix Operations
Operations performed on arrays are done in an *elementwise* fashion